Added compatibility for latest testing suite.
mediact/coding-standard-phpstorm pull request #19
Opened 2021-03-10 16:01 UTC by leonhelmus

* Added ext-simplexml as a requirement.
* Fixed unit tests to make it compatible with phpunit ^9.0

2021-03-11 08:03 UTC, ksangers requested changes

2021-03-11 08:03 UTC, ksangers commented on tests/FilesystemTest.php
> +        $this->expectException(\RuntimeException::class);
Nitpicky here. Please `use` the class. Same for others below

2021-03-11 08:03 UTC, ksangers commented on tests/XmlAccessorTest.php
> +        $this->expectException(\InvalidArgumentException::class);
As earlier: `use`

2021-03-17 08:48 UTC, ashokadewit approved these changes

2021-03-19 13:50 UTC, ksangers approved these changes

2021-03-19 13:51 UTC, ksangers commented
@leonhelmus can you get this to run through scrutinizer as well?

2021-03-24 14:14 UTC, leonhelmus commented
Fixed it and merging it now.

2021-03-24 14:14 UTC, merged